# Generated by Django 3.0.8 on 2020-07-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appUser',
            fields=[
                ('Name', models.CharField(max_length=36)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Username', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=11, unique=True)),
            ],
        ),
    ]
