# Generated by Django 3.0.8 on 2020-07-25 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='appuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('num_of_post', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        AddDefaultValue(
            model_name = 'appuser',
            name = 'id',
            value = -1
        ),
        AddDefaultValue(
            model_name = 'appuser',
            name = 'bio',
            value = "Please add your bio here."
        ),
        AddDefaultValue(
            model_name = 'appuser',
            name = 'num_of_post',
            value = "0"
        ),
        AddDefaultValue(
            model_name = 'appuser',
            name = 'image',
            value = "profile_pics/default.jpg"
        )

    ]
