# Generated by Django 2.0.7 on 2020-07-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0002_auto_20200726_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='image',
        ),
    ]
