# Generated by Django 3.0.8 on 2020-08-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apartment',
            fields=[
                ('ApartmentID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=60, unique=True)),
                ('Description_a', models.TextField(blank=True)),
                ('Location', models.TextField(blank=True)),
                ('Email', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=11)),
                ('Pet_friendly', models.IntegerField()),
                ('Printer', models.IntegerField()),
                ('Swimming_pool', models.IntegerField()),
                ('Gym', models.IntegerField()),
                ('Latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('Longitude', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
        ),
    ]
