# Generated by Django 3.0.8 on 2020-07-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apartment',
            fields=[
                ('ApartmentID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=60, unique=True)),
                ('Description', models.TextField(blank=True)),
                ('Location', models.TextField(blank=True)),
                ('Email', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=11)),
                ('Pet_friendly', models.BooleanField()),
                ('Printer', models.BooleanField()),
                ('Swimming_pool', models.BooleanField()),
                ('Gym', models.BooleanField()),
            ],
        ),
    ]
