# Generated by Django 2.0.7 on 2020-07-26 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartment', '0001_initial'),
        ('appUser', '0003_remove_appuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('Post_id', models.AutoField(primary_key=True, serialize=False)),
                ('Pub_date', models.DateTimeField(verbose_name='data posted')),
                ('Apartment', models.CharField(max_length=60)),
                ('Post_title', models.TextField()),
                ('Description', models.TextField(blank=True)),
                ('Move_in_date', models.DateField()),
                ('Move_out_date', models.DateField()),
                ('Duration', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Exist', models.BooleanField(default=True)),
                ('Bedroom', models.IntegerField()),
                ('Bathroom', models.IntegerField()),
                ('Likes', models.IntegerField()),
                ('ApartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.apartment')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appUser.appUser')),
            ],
        ),
    ]
