# Generated by Django 3.0.8 on 2020-08-02 23:01

from django.db import migrations, models
import django.db.models.deletion
from django_add_default_value import AddDefaultValue
import MySQLdb


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appUser', '0001_initial'),
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('Post_id', models.AutoField(primary_key=True, serialize=False)),
                ('Pub_date', models.DateTimeField(verbose_name='data posted')),
                ('Apartment', models.CharField(max_length=60)),
                ('Post_title', models.TextField()),
                ('Description', models.TextField(blank=True)),
                ('Move_in_date', models.DateField()),
                ('Move_out_date', models.DateField()),
                ('Duration', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Exist', models.BooleanField(default=True)),
                ('Bedroom', models.IntegerField()),
                ('Bathroom', models.IntegerField()),
                ('Likes', models.IntegerField()),
                ('Views', models.IntegerField()),
                ('ApartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.apartment')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appUser.appUser')),
            ],
        ),
        AddDefaultValue(
            model_name = 'post',
            name = 'Likes',
            value = 0
        ),
        AddDefaultValue(
            model_name = 'post',
            name = 'Exist',
            value = True
        ),
        AddDefaultValue(
            model_name = 'post',
            name = 'Views',
            value = 1
        ),
        migrations.CreateModel(
            name='view_history',
            fields=[
                ('View_time', models.DateTimeField(primary_key=True, serialize=False)),
                ('Post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appUser.appUser')),
            ],
        ),
        migrations.CreateModel(
            name='search_history',
            fields=[
                ('Search_time', models.DateTimeField(primary_key=True, serialize=False)),
                ('Move_in_date', models.DateField()),
                ('Move_out_date', models.DateField()),
                ('Duration', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Bedroom', models.IntegerField()),
                ('Bathroom', models.IntegerField()),
                ('Pet_friendly', models.IntegerField()),
                ('Printer', models.IntegerField()),
                ('Swimming_pool', models.IntegerField()),
                ('Gym', models.IntegerField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appUser.appUser')),
            ],
        ),
        # AddDefaultValue(
        #     model_name = 'search_history',
        #     name = 'Move_in_date',
        #     value = "NULL"
        # ),
        # AddDefaultValue(
        #     model_name = 'search_history',
        #     name = 'Move_out_date',
        #     value = None
        # ),
        # AddDefaultValue(
        #     model_name = 'search_history',
        #     name = 'Duration',
        #     value = None
        # ),
        # AddDefaultValue(
        #     model_name = 'search_history',
        #     name = 'Price',
        #     value = None
        # ),
        # AddDefaultValue(
        #     model_name = 'search_history',
        #     name = 'Bedroom',
        #     value = None
        # ),
        # AddDefaultValue(
        #     model_name = 'search_history',
        #     name = 'Bathroom',
        #     value = None
        # ),
        # AddDefaultValue(
        #     model_name = 'search_history',
        #     name = 'Pet_friendly',
        #     value = None
        # ),
        # AddDefaultValue(
        #     model_name = 'search_history',
        #     name = 'Printer',
        #     value = None
        # ),
        # AddDefaultValue(
        #     model_name = 'search_history',
        #     name = 'Swimming_pool',
        #     value = None
        # ),
        # AddDefaultValue(
        #     model_name = 'search_history',
        #     name = 'Gym',
        #     value = None
        # ),
    ]
