# Generated by Django 3.0.8 on 2020-07-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200724_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='Like',
            field=models.IntegerField(default=2),
        ),
    ]
